// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderItem = "order_items"

// OrderItem mapped from table <order_items>
type OrderItem struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   *int32         `gorm:"column:order_id" json:"order_id"`
	BookID    *int32         `gorm:"column:book_id" json:"book_id"`
	Quantity  *int32         `gorm:"column:quantity" json:"quantity"`
	Price     *float64       `gorm:"column:price" json:"price"`
	CreatedAt *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	CreatedBy *string        `gorm:"column:created_by" json:"created_by"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UpdatedBy *string        `gorm:"column:updated_by" json:"updated_by"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy *string        `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
