// Code generated by mockery v2.43.2. DO NOT EDIT.

package base

import mock "github.com/stretchr/testify/mock"

// MockIDBConnection is an autogenerated mock type for the IDBConnection type
type MockIDBConnection[TDBConnection interface{}] struct {
	mock.Mock
}

type MockIDBConnection_Expecter[TDBConnection interface{}] struct {
	mock *mock.Mock
}

func (_m *MockIDBConnection[TDBConnection]) EXPECT() *MockIDBConnection_Expecter[TDBConnection] {
	return &MockIDBConnection_Expecter[TDBConnection]{mock: &_m.Mock}
}

// GetDBConnection provides a mock function with given fields:
func (_m *MockIDBConnection[TDBConnection]) GetDBConnection() TDBConnection {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDBConnection")
	}

	var r0 TDBConnection
	if rf, ok := ret.Get(0).(func() TDBConnection); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(TDBConnection)
	}

	return r0
}

// MockIDBConnection_GetDBConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDBConnection'
type MockIDBConnection_GetDBConnection_Call[TDBConnection interface{}] struct {
	*mock.Call
}

// GetDBConnection is a helper method to define mock.On call
func (_e *MockIDBConnection_Expecter[TDBConnection]) GetDBConnection() *MockIDBConnection_GetDBConnection_Call[TDBConnection] {
	return &MockIDBConnection_GetDBConnection_Call[TDBConnection]{Call: _e.mock.On("GetDBConnection")}
}

func (_c *MockIDBConnection_GetDBConnection_Call[TDBConnection]) Run(run func()) *MockIDBConnection_GetDBConnection_Call[TDBConnection] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDBConnection_GetDBConnection_Call[TDBConnection]) Return(_a0 TDBConnection) *MockIDBConnection_GetDBConnection_Call[TDBConnection] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDBConnection_GetDBConnection_Call[TDBConnection]) RunAndReturn(run func() TDBConnection) *MockIDBConnection_GetDBConnection_Call[TDBConnection] {
	_c.Call.Return(run)
	return _c
}

// NewMockIDBConnection creates a new instance of MockIDBConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDBConnection[TDBConnection interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDBConnection[TDBConnection] {
	mock := &MockIDBConnection[TDBConnection]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
